name: Lint Codebase

on:
  push:
    branches:
      - custom # Adjust to your preferred branch
  pull_request:
    branches:
      - custom

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint --max-warnings=0

  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # You can use the Node version of your choice

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        run: |
          npm run test -- --ci --coverage --maxWorkers=2  # Adjust based on your test script
        env:
          CI: true # Ensures Jest runs in CI mode (optimizes for CI)
